name: CI
on:
    pull_request:
    push:
        branches:
            - master
        tags:
            - 'v*.*.*'

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # Required for local tests
            - name: Setup MetaCall CLI
              run: wget -O - https://raw.githubusercontent.com/metacall/install/master/install.sh | sh

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  registry-url: https://registry.npmjs.org

            - name: Installing Dependencies
              run: npm i

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build

            - name: Run Tests (local)
              run: |
                  export TEST_DEPLOY_LOCAL="true"
                  npm install -g @metacall/faas
                  metacall-faas &
                  sleep 10
                  npm run coverage

            - name: Run Tests (production)
              if: github.event_name != 'pull_request'
              run: |
                  touch .env
                  echo 'METACALL_AUTH_EMAIL="${{ secrets.METACALL_AUTH_EMAIL }}"' >> .env
                  echo 'METACALL_AUTH_PASSWORD="${{ secrets.METACALL_AUTH_PASSWORD }}"' >> .env
                  npm run coverage

            - name: Publish
              uses: JS-DevTools/npm-publish@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  access: 'public'
                  token: '${{ secrets.NPM_AUTH_TOKEN }}'
